DATA:
  RAW:
    DIR: /mnt/storage/idl-0/bio/boxiang/sim_anneal/data/raw
    # Spike protein:
    SPIKE: /mnt/storage/idl-0/bio/boxiang/sim_anneal/data/raw/spike.fasta 
    # Human codon frequencies:
    CODON: /mnt/storage/idl-0/bio/boxiang/sim_anneal/data/raw/codon_usage_freq_table_human.csv
    # Reference points for making MFE-CAI plot:
    REF_P: /mnt/storage/idl-0/bio/boxiang/sim_anneal/data/raw/new_SPIKE_MFE_CAI_curve_human.csv
  PROCESSED:
    DIR: /mnt/storage/idl-0/bio/boxiang/sim_anneal/data/processed/
    CAI_RANDOM: /mnt/storage/idl-0/bio/boxiang/sim_anneal/data/processed/cai_random/
FIGURE:
  DIR: /mnt/storage/idl-0/bio/boxiang/sim_anneal/figure/
BIN:
  LINEARFOLD: "/mnt/storage/idl-0/bio/boxiang/sim_anneal/scripts/bin/LinearFold_d0_version/linearfold -V -b -1"
  RNAFOLD: "RNAfold -d0"
