DATA:
  RAW:
    DIR: /Users/boxiang/Documents/!-work/Baidu/projects/sim_anneal/data/raw
    # Spike protein:
    SPIKE: /Users/boxiang/Documents/!-work/Baidu/projects/sim_anneal/data/raw/spike.fasta 
    # Human codon frequencies:
    CODON_FREQ: /Users/boxiang/Documents/!-work/Baidu/projects/sim_anneal/data/raw/codon_usage_freq_table_human.csv
    # Codon table:
    CODON_TABLE: /Users/boxiang/Documents/!-work/Baidu/projects/sim_anneal/data/raw/coding_wheel.txt
    # Reference points for making MFE-CAI plot:
    REF_P: /Users/boxiang/Documents/!-work/Baidu/projects/sim_anneal/data/raw/new_SPIKE_MFE_CAI_curve_human.csv
  PROCESSED:
    DIR: /Users/boxiang/Documents/!-work/Baidu/projects/sim_anneal/data/processed/
    CAI_RANDOM: /Users/boxiang/Documents/!-work/Baidu/projects/sim_anneal/data/processed/cai_random/
    CAI_ANNEAL: /Users/boxiang/Documents/!-work/Baidu/projects/sim_anneal/data/processed/cai_sim_anneal/
FIGURE:
  DIR: /Users/boxiang/Documents/!-work/Baidu/projects/sim_anneal/figure/
BIN:
  LINEARFOLD: "/Users/boxiang/Documents/!-work/Baidu/projects/sim_anneal/scripts/bin/LinearFold_d0_version/linearfold -V -b -1"
  RNAFOLD: "RNAfold -d0"